### PR TITLE
chore: 🤖 add benchmark

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
1. `3m.json` is a big json which file size is 3M, test for big file parsing performance.
2. `tsconfig.json`  is a json file generated by `tsc --init`, which is heavily commented json file. test for comment parsing performance.
3. `package.json` is a json file copy from `vscode` repository, bigger than most other `package.json`, test for normal json parsing performance.  

I think these three json file would cover most scenario. What do you think ? cc @dsherret

**Comment by dsherret** [comment]
It looks good! Thanks! It would also be good to get a large file similar to 3M.json, but that is formatted so it displays on multiple lines.

What's the copyright on 3M.json? Where did you get that file? Maybe add a comment at the top of that file that shows where it's from.

If you sign the CLA I can merge this soon.

**Comment by IWANABETHATGUY** [comment]
3mb json data came from here https://datahub.io/datahq/1mb-test/r/1mb-test.json, I am not sure If the test json data has copyright

**Comment by dsherret** [comment]
@IWANABETHATGUY yeah, looks like there's no license listed on the file so I don't think we can use it here https://datahub.io/datahq/1mb-test

**Pull request merged**
