### PR TITLE
perf: ⚡️ perf parse-value

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
my computer: 
current:
```
running 6 tests
test citm_catalog_json_large_ast   ... bench:  69,412,450 ns/iter (+/- 25,243,601)
test citm_catalog_json_large_value ... bench:  88,551,560 ns/iter (+/- 38,142,516)
test package_json_ast              ... bench:      88,635 ns/iter (+/- 13,077)
test package_json_value            ... bench:     103,713 ns/iter (+/- 7,369)
test tsconfig_json_ast             ... bench:      32,696 ns/iter (+/- 14,447)
test tsconfig_json_value           ... bench:      32,818 ns/iter (+/- 1,638)

test result: ok. 0 passed; 0 failed; 0 ignored; 6 measured; 0 filtered out; finished in 62.98s
```
before: 
```
running 6 tests
test citm_catalog_json_large_ast   ... bench:  68,363,600 ns/iter (+/- 15,877,140)
test citm_catalog_json_large_value ... bench:  96,260,580 ns/iter (+/- 22,216,507)
test package_json_ast              ... bench:     103,069 ns/iter (+/- 50,363)
test package_json_value            ... bench:     117,762 ns/iter (+/- 38,949)
test tsconfig_json_ast             ... bench:      28,376 ns/iter (+/- 2,011)
test tsconfig_json_value           ... bench:      29,111 ns/iter (+/- 1,894)

test result: ok. 0 passed; 0 failed; 0 ignored; 6 measured; 0 filtered out; finished in 67.75s

```

**Comment by IWANABETHATGUY** [comment]
cc @dsherret， could you help for review?

**Comment by dsherret** [comment]
Hey @IWANABETHATGUY, thanks for this. It is a little bit faster, but I would prefer to keep the public API only have std types. We could wrap it, but it seems that fxhash does not prevent against DDOS which I could see being a feature people would want in some use cases.

I previously took a look at what serde_json does here and they use a BTreeMap. My guess would be that it will be faster for parsing, but I would guess lookups will be slower depending on the size of the collection. I think in most cases people will be parsing small files so it would probably be better overall. You may want to try switching this to std::collections::BTreeMap.

**Comment by IWANABETHATGUY** [comment]
using BTreeMap
```
test citm_catalog_json_large_ast   ... bench:  78,636,360 ns/iter (+/- 13,782,568)
test citm_catalog_json_large_value ... bench:  98,731,780 ns/iter (+/- 12,531,601)
test package_json_ast              ... bench:      99,940 ns/iter (+/- 50,865)
test package_json_value            ... bench:     139,453 ns/iter (+/- 52,373)
test tsconfig_json_ast             ... bench:      37,636 ns/iter (+/- 6,581)
test tsconfig_json_value           ... bench:      38,800 ns/iter (+/- 9,324)
```
std::HashMap
```running 6 tests
test citm_catalog_json_large_ast   ... bench:  80,079,050 ns/iter (+/- 15,920,799)
test citm_catalog_json_large_value ... bench: 107,082,760 ns/iter (+/- 15,669,294)
test package_json_ast              ... bench:      94,383 ns/iter (+/- 20,151)
test package_json_value            ... bench:     131,700 ns/iter (+/- 26,319)
test tsconfig_json_ast             ... bench:      31,697 ns/iter (+/- 7,448)
test tsconfig_json_value           ... bench:      32,712 ns/iter (+/- 9,258)
```
In fact, BTreeMap is slower than std::HashMap

**Comment by dsherret** [comment]
Thanks for investing! That is interesting. I wonder why they used it.

**Comment by IWANABETHATGUY** [comment]
> but I would prefer to keep the public API only have std types. We could wrap it.      

fxhash is pretty small, it would not introduce to much binary size, also I found that we already use `serde_json` as dependency.

> but it seems that fxhash does not prevent against DDOS which I could see being a feature people would want in some use cases.   

I am not sure who would use the user uploaded json as direct input and then do some logic, this sounds pretty weird, using `json with comments` as directly input sounds more weird. 



I previously took a look at what serde_json does here and they use a BTreeMap. My guess would be that it will be faster for parsing, but I would guess lookups will be slower depending on the size of the collection. I think in most cases people will be parsing small files so it would probably be better overall. You may want to try switching this to std::collections::BTreeMap.

**Comment by IWANABETHATGUY** [comment]
> Thanks for investing! That is interesting. I wonder why they used it.

I am pretty sure , HashMap is faster than BTreeMap in most scenario, HashMap lookup just use nearly O(1), BTreeMap need O(h)

https://github.com/Rufflewind/bench-maps, here is the benchmark.
I guess they want the json entry by order?

**Pull request closed without merging**
