### PR TITLE
[WIP]perf: ⚡️ change the immutableString to smol_str

### LINKED ISSUE #10: Reference the original string as much as possible
This should be changed to point at the original string as much as possible. Before doing this though, benchmarks should be created in #9.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
resolve #10

### CODE REVIEW

**Comment by IWANABETHATGUY** [comment]
this branch will merge after the bench merged in master

**Comment by IWANABETHATGUY** [comment]
> Unlike String, however, SmolStr is immutable. The primary use case for SmolStr is a good enough default storage for tokens of typical programming languages. Strings consisting of a series of newlines, followed by a series of whitespace are a typical pattern in computer programs because of indentation. Note that a specialized interner might be a better solution for some use cases.
like the docs said, the smol_str is heavily optimized for parser infra.

**Comment by dsherret** [comment]
Hey @IWANABETHATGUY, thanks, but I recommend opening issues first and discussing before doing work so you don't waste time. We need to get #9 in before any perf improvements, I don't want to introduce any dependencies to the public API of this crate (I'd prefer for this to have no dependencies), and this will all change a lot when #10 is in. After #9 then #10 is done then I think we can think about this. So sorry, but I won't be accepting any perf improvements until #9 is in. If you would like to help out with #9 I would be most grateful though!

**Comment by IWANABETHATGUY** [comment]
hi @dsherret, so that's why i make this a `draft`, and mark this as `WIP` in the title

**Pull request closed without merging**
