### PR TITLE
perf: ⚡️ perf scanner

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by dsherret** [comment]
Thanks @IWANABETHATGUY! Question though: since this is only created once per format, does using small-vec mean it will be faster for access and storage? If so, maybe we should just create our own wrapper around a fixed size array instead of having a new dependency. Would you be up for that?

**Comment by IWANABETHATGUY** [comment]
> 

Since this pull request is only inproved when the json file is large, i agree with you, i am gona close this.

**Comment by dsherret** [comment]
How much does it help for large files? Maybe it would be better though.

**Comment by IWANABETHATGUY** [comment]
> How much does it help for large files? Maybe it would be better though.

About 14% acording the github ci benchmark, but has some regression in small json file like `tsconfig.json`, so i think maybe i should investigate other way

**Comment by IWANABETHATGUY** [comment]
Also, I am a bit curious why not we use `CST` instead, since this crate most used in formating.

**Comment by dsherret** [comment]
I find the github benchmark to be really inaccurate on single runs. It's probably the same speed for small files.

I am just more familiar with ASTs, but ASTs should potentially be faster because they use less memory. For formatting I've found I actually prefer keeping the comments and tokens stored separately. In a CST sometimes the author of the parser puts the comments or tokens at an annoying level of the tree.

**Comment by dsherret** [comment]
I just tried this out and it is slower unfortunately.

```
Before:

test citm_catalog_json_large_ast   ... bench:  50,640,770 ns/iter (+/- 17,030,563)
test citm_catalog_json_large_value ... bench:  75,590,240 ns/iter (+/- 5,299,043)
test package_json_ast              ... bench:      59,282 ns/iter (+/- 4,208)
test package_json_value            ... bench:      88,683 ns/iter (+/- 2,975)
test tsconfig_json_ast             ... bench:      21,817 ns/iter (+/- 986)
test tsconfig_json_value           ... bench:      22,613 ns/iter (+/- 1,021)

After:

test citm_catalog_json_large_ast   ... bench:  55,352,620 ns/iter (+/- 17,208,676)
test citm_catalog_json_large_value ... bench:  78,259,440 ns/iter (+/- 4,393,609)
test package_json_ast              ... bench:      72,450 ns/iter (+/- 2,560)
test package_json_value            ... bench:     100,816 ns/iter (+/- 2,905)
test tsconfig_json_ast             ... bench:      28,954 ns/iter (+/- 995)
test tsconfig_json_value           ... bench:      29,908 ns/iter (+/- 1,311)
```

**Pull request closed without merging**
